local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, {desc = "find project file"})
vim.keymap.set('n', '<C-p>', builtin.git_files, {desc = "find git files (ignore non-git files)"})
vim.keymap.set('n', '<leader>ps', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end, {desc = "Find word"})
vim.keymap.set('n', '<leader>fg', builtin.live_grep, {desc = "live grep"})
